version: '3.9'
services:
  ttb-assignment:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ttb-assg?currentSchema=customer
      - SPRING_DATASOURCE_USERNAME=ttb-admin
      - SPRING_DATASOURCE_PASSWORD=ttb-assg
    depends_on:
      - postgres
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ttb-assg
      - POSTGRES_USER=ttb-admin
      - POSTGRES_DB=ttb-assg
volumes:  # Volume definition at the top level
  postgres_data: