version: '3.9'
services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ttb-assg
      - POSTGRES_USER=ttb-admin
      - POSTGRES_DB=ttb-assg
volumes:  # Volume definition at the top level
  postgres_data: